site_name: Eveeye Documentation
repo_url: https://github.com/Risingson/eedocs/
theme:
  name: rtd-dropdown
markdown_extensions:
  - admonition  
  - footnotes
extra_css: [css/extra.css]
nav:
- Eveeye Explorer Docs: index.md
- Desktop app: desktop-app.md
- Credits: credits.md
- User Interface:
    - Basics: user-interface/basic-user-interface.md
    - Settings: user-interface/settings.md
    - Search Interface: user-interface/search.md
    - Solarsystem Info: user-interface/solarsystem-info.md
- Map:
    - Layout: map/layout.md
    - Shapes: map/shapes.md   
    - Chain Mapping: map/chain-mapping.md
- Data Displays:   
    - Overview: data/overview.md
    - Presets: data/presets.md
    - Nodes: data/node.md
    - Labels: data/label.md
    - Sectors: data/sector.md
    - Constellation Outlines: data/constellation.md
    - Tags: data/tag.md
    - Miscellaneous: data/misc.md
- Client Sync:
    - Character Management: sync/character-management.md
    - Client Sync: sync/client-synchronisation.md    
- Data Sharing:    
    - Data Sharing: sharing/data-sharing-overview.md
    - Intel Channels: sharing/intel-channels.md
    - Signatures: sharing/signatures.md   
    - Custom Marks: sharing/custom-marks.md 

