site_name: Eveeye Documentation
repo_url: https://github.com/Risingson/eedocs/
theme:
  name: rtd-dropdown
markdown_extensions:
  - admonition  
  - footnotes
extra_css: [css/extra.css]
nav:
- Eveeye Explorer Docs: index.md
- User Interface:
    - Basics: ui/basic-ui.md
    - Settings: ui/settings.md
    - Search Interface: ui/search.md
    - Solarsystem Info: ui/solarsystem-info.md
    - Bookmarks: ui/bookmarks.md
    - Legend: ui/legend.md
- Map:
    - Layout: map/layout.md
    - Shapes: map/shapes.md   
    - Chain Mapping: map/chain-mapping.md
- Data Displays:   
    - Overview: data/overview.md
    - Presets: data/presets.md
    - Nodes: data/node.md
    - Labels: data/label.md
    - Sectors: data/sector.md
    - Constellation Outlines: data/constellation.md
    - Tags: data/tag.md
    - Miscellaneous: data/misc.md
- Client Sync:
    - Character Management: sync/character-management.md
    - Client Sync: sync/client-synchronisation.md 
    - Waypoints: sync/waypoints.md 
- Data Sharing:    
    - Cloud: sharing/cloud.md
    - Intel Channels: sharing/intel-channels.md
    - Signatures: sharing/signatures.md   
    - Jump Bridges: sharing/jumpbridges.md
    - Custom Marks: sharing/custom-marks.md 
- Miscellaneous:   
    - Desktop app: desktop-app.md
    - Release Notes: release-notes.md
    - Credits: credits.md
    - Privacy and Terms: privacy.md
