site_name: Eveeye Documentation
repo_url: https://github.com/Risingson/eedocs/
theme:
  name: rtd-dropdown
markdown_extensions:
  - admonition  
  - footnotes
extra_css: [css/extra.css]
nav:
- Eveeye Explorer Docs: index.md
- Desktop app: desktop-app.md
- Credits: credits.md
- User Interface:
    - Basics: user-interface/basic-user-interface.md
    - Settings: user-interface/settings.md
    - Search Interface: user-interface/search.md
    - Solarsystem Info: user-interface/solarsystem-info.md
- Map:
    - Map Layouts: map/layout.md
    - Map Shapes: map/shapes.md   
    - Chain Mapping: map/chain-mapping.md
- Data Displays:   
    - Overview: data/map-options-overview.md
    - Presets: data/map-options-presets.md
    - Nodes: data/map-options-node.md
    - Labels: data/map-options-label.md
    - Sectors: data/map-options-sector.md
    - Constellation Outlines: data/map-options-con.md
    - Tags: data/map-options-tag.md
    - Miscellaneous: data/map-options-misc.md
- Client Sync:
    - Character Management: sync/character-management.md
    - Client Sync: sync/client-synchronisation.md    
- Data Sharing:    
    - Data Sharing: sharing/data-sharing-overview.md
    - Intel Channels: sharing/intel-channels.md
    - Signatures: sharing/signatures.md   
    - Custom Marks: sharing/custom-marks.md 

